// packages/web/app/documents/page.tsx
'use client';

import { useState, useEffect } from 'react';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import { Button } from '@/components/ui/button';
import { Badge } from '@/components/ui/badge';
import { Checkbox } from '@/components/ui/checkbox';
import { Textarea } from '@/components/ui/textarea';
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from '@/components/ui/select';
import { Separator } from '@/components/ui/separator';
import { 
  Eye, 
  CheckCircle, 
  XCircle, 
  FileText, 
  Image, 
  FileImage,
  Download,
  AlertCircle
} from 'lucide-react';

interface ValidationCheck {
  id: string;
  label: string;
  description?: string;
  required: boolean;
}

interface ValidationTemplate {
  documentType: string;
  checks: ValidationCheck[];
  instructions?: string;
}

interface Document {
  id: string;
  name: string;
  type: string;
  url: string;
  status: 'PENDING' | 'APPROVED' | 'REJECTED';
  student: {
    id: string;
    name: string;
    crefito: string;
  };
  validationChecks?: Record<string, boolean>;
  validationNotes?: string;
  rejectionReason?: string;
  uploadedAt: string;
  validationTemplate?: ValidationTemplate;
}

export default function DocumentsPage() {
  const [documents, setDocuments] = useState<Document[]>([]);
  const [selectedDocument, setSelectedDocument] = useState<Document | null>(null);
  const [validationChecks, setValidationChecks] = useState<Record<string, boolean>>({});
  const [notes, setNotes] = useState('');
  const [rejectionReason, setRejectionReason] = useState('');
  const [loading, setLoading] = useState(true);
  const [statusFilter, setStatusFilter] = useState<string>('PENDING');

  useEffect(() => {
    fetchDocuments();
  }, [statusFilter]);

  const fetchDocuments = async () => {
    try {
      const response = await fetch(`/api/documents?status=${statusFilter}&limit=50`);
      const data = await response.json();
      if (data.success) {
        setDocuments(data.data);
      }
    } catch (error) {
      console.error('Error fetching documents:', error);
    } finally {
      setLoading(false);
    }
  };

  const fetchDocument = async (id: string) => {
    try {
      const response = await fetch(`/api/documents/${id}`);
      const data = await response.json();
      if (data.success) {
        setSelectedDocument(data.data);
        setValidationChecks(data.data.validationChecks || {});
        setNotes(data.data.validationNotes || '');
      }
    } catch (error) {
      console.error('Error fetching document:', error);
    }
  };

  const updateValidationChecks = async () => {
    if (!selectedDocument) return;

    try {
      const response = await fetch(`/api/documents/${selectedDocument.id}/validation`, {
        method: 'PATCH',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ validationChecks, notes }),
      });

      if (response.ok) {
        // Refresh the document list
        fetchDocuments();
      }
    } catch (error) {
      console.error('Error updating validation checks:', error);
    }
  };

  const approveDocument = async () => {
    if (!selectedDocument) return;

    try {
      const response = await fetch(`/api/documents/${selectedDocument.id}/approve`, {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ notes }),
      });

      if (response.ok) {
        setSelectedDocument(null);
        fetchDocuments();
      }
    } catch (error) {
      console.error('Error approving document:', error);
    }
  };

  const rejectDocument = async () => {
    if (!selectedDocument || !rejectionReason) return;

    try {
      const response = await fetch(`/api/documents/${selectedDocument.id}/reject`, {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ reason: rejectionReason, notes }),
      });

      if (response.ok) {
        setSelectedDocument(null);
        setRejectionReason('');
        fetchDocuments();
      }
    } catch (error) {
      console.error('Error rejecting document:', error);
    }
  };

  const getStatusBadge = (status: string) => {
    switch (status) {
      case 'PENDING':
        return <Badge variant="secondary">Pendente</Badge>;
      case 'APPROVED':
        return <Badge variant="default" className="bg-green-500">Aprovado</Badge>;
      case 'REJECTED':
        return <Badge variant="destructive">Rejeitado</Badge>;
      default:
        return <Badge variant="outline">{status}</Badge>;
    }
  };

  const getDocumentIcon = (type: string) => {
    switch (type) {
      case 'VACCINATION_CARD':
        return <FileText className="h-4 w-4" />;
      case 'BADGE_PICTURE':
        return <Image className="h-4 w-4" />;
      default:
        return <FileImage className="h-4 w-4" />;
    }
  };

  const getDocumentTypeLabel = (type: string) => {
    switch (type) {
      case 'VACCINATION_CARD':
        return 'Carteira de Vacinação';
      case 'PROFESSIONAL_ID':
        return 'Identidade Profissional';
      case 'COMMITMENT_CONTRACT':
        return 'Termo de Compromisso';
      case 'ADMISSION_FORM':
        return 'Ficha de Admissão';
      case 'BADGE_PICTURE':
        return 'Foto do Crachá';
      case 'INSURANCE_DOCUMENTATION':
        return 'Documentação de Seguro';
      default:
        return type;
    }
  };

  if (loading) {
    return (
      <div className="flex items-center justify-center h-64">
        <div className="text-center">
          <div className="animate-spin rounded-full h-8 w-8 border-b-2 border-gray-900 mx-auto"></div>
          <p className="mt-2">Carregando documentos...</p>
        </div>
      </div>
    );
  }

  return (
    <div className="container mx-auto p-6">
      <div className="flex justify-between items-center mb-6">
        <h1 className="text-3xl font-bold">Validação de Documentos</h1>
        <Select value={statusFilter} onValueChange={setStatusFilter}>
          <SelectTrigger className="w-48">
            <SelectValue placeholder="Filtrar por status" />
          </SelectTrigger>
          <SelectContent>
            <SelectItem value="PENDING">Pendentes</SelectItem>
            <SelectItem value="APPROVED">Aprovados</SelectItem>
            <SelectItem value="REJECTED">Rejeitados</SelectItem>
          </SelectContent>
        </Select>
      </div>

      <div className="grid grid-cols-1 lg:grid-cols-3 gap-6">
        {/* Document List */}
        <div className="lg:col-span-1">
          <Card>
            <CardHeader>
              <CardTitle>Documentos ({documents.length})</CardTitle>
            </CardHeader>
            <CardContent>
              <div className="space-y-2 max-h-96 overflow-y-auto">
                {documents.map((doc) => (
                  <div
                    key={doc.id}
                    className={`p-3 border rounded-lg cursor-pointer hover:bg-gray-50 ${
                      selectedDocument?.id === doc.id ? 'bg-blue-50 border-blue-200' : ''
                    }`}
                    onClick={() => fetchDocument(doc.id)}
                  >
                    <div className="flex items-center justify-between">
                      <div className="flex items-center space-x-2">
                        {getDocumentIcon(doc.type)}
                        <div>
                          <p className="font-medium text-sm">{doc.student.name}</p>
                          <p className="text-xs text-gray-500">{getDocumentTypeLabel(doc.type)}</p>
                        </div>
                      </div>
                      {getStatusBadge(doc.status)}
                    </div>
                  </div>
                ))}
              </div>
            </CardContent>
          </Card>
        </div>

        {/* Document Viewer and Validation */}
        <div className="lg:col-span-2">
          {selectedDocument ? (
            <Card>
              <CardHeader>
                <CardTitle className="flex items-center justify-between">
                  <span>Validar Documento</span>
                  {getStatusBadge(selectedDocument.status)}
                </CardTitle>
              </CardHeader>
              <CardContent className="space-y-6">
                {/* Document Info */}
                <div className="grid grid-cols-2 gap-4 text-sm">
                  <div>
                    <p className="font-medium">Estudante:</p>
                    <p>{selectedDocument.student.name}</p>
                    <p className="text-gray-500">CREFITO: {selectedDocument.student.crefito}</p>
                  </div>
                  <div>
                    <p className="font-medium">Tipo:</p>
                    <p>{getDocumentTypeLabel(selectedDocument.type)}</p>
                    <p className="text-gray-500">Enviado em: {new Date(selectedDocument.uploadedAt).toLocaleDateString('pt-BR')}</p>
                  </div>
                </div>

                <Separator />

                {/* Document Display */}
                <div>
                  <h3 className="font-medium mb-2">Visualizar Documento</h3>
                  <div className="border rounded-lg p-4 bg-gray-50">
                    <div className="flex items-center justify-between mb-2">
                      <span className="text-sm text-gray-600">{selectedDocument.name}</span>
                      <Button variant="outline" size="sm" onClick={() => window.open(selectedDocument.url, '_blank')}>
                        <Download className="h-4 w-4 mr-1" />
                        Abrir
                      </Button>
                    </div>
                    <div className="bg-white border rounded p-4 min-h-64 flex items-center justify-center">
                      {selectedDocument.type === 'BADGE_PICTURE' ? (
                        <img 
                          src={selectedDocument.url} 
                          alt="Document" 
                          className="max-w-full max-h-64 object-contain"
                        />
                      ) : (
                        <div className="text-center text-gray-500">
                          <FileText className="h-12 w-12 mx-auto mb-2" />
                          <p>Clique em "Abrir" para visualizar o documento</p>
                        </div>
                      )}
                    </div>
                  </div>
                </div>

                <Separator />

                {/* Validation Checks */}
                {selectedDocument.validationTemplate && (
                  <div>
                    <h3 className="font-medium mb-2">Critérios de Validação</h3>
                    {selectedDocument.validationTemplate.instructions && (
                      <p className="text-sm text-gray-600 mb-3">{selectedDocument.validationTemplate.instructions}</p>
                    )}
                    <div className="space-y-2">
                      {selectedDocument.validationTemplate.checks.map((check) => (
                        <div key={check.id} className="flex items-center space-x-2">
                          <Checkbox
                            id={check.id}
                            checked={validationChecks[check.id] || false}
                            onCheckedChange={(checked) => {
                              setValidationChecks(prev => ({
                                ...prev,
                                [check.id]: checked as boolean
                              }));
                            }}
                          />
                          <label htmlFor={check.id} className="text-sm flex items-center">
                            {check.label}
                            {check.required && <AlertCircle className="h-3 w-3 ml-1 text-red-500" />}
                          </label>
                        </div>
                      ))}
                    </div>
                  </div>
                )}

                <Separator />

                {/* Notes */}
                <div>
                  <h3 className="font-medium mb-2">Observações</h3>
                  <Textarea
                    placeholder="Adicione observações sobre a validação..."
                    value={notes}
                    onChange={(e) => setNotes(e.target.value)}
                    rows={3}
                  />
                </div>

                {/* Rejection Reason */}
                {selectedDocument.status === 'PENDING' && (
                  <div>
                    <h3 className="font-medium mb-2">Motivo da Rejeição</h3>
                    <Textarea
                      placeholder="Motivo da rejeição (obrigatório para rejeitar)..."
                      value={rejectionReason}
                      onChange={(e) => setRejectionReason(e.target.value)}
                      rows={2}
                    />
                  </div>
                )}

                {/* Action Buttons */}
                {selectedDocument.status === 'PENDING' && (
                  <div className="flex space-x-2">
                    <Button 
                      variant="outline" 
                      onClick={updateValidationChecks}
                      className="flex-1"
                    >
                      <Eye className="h-4 w-4 mr-1" />
                      Salvar Verificação
                    </Button>
                    <Button 
                      onClick={approveDocument}
                      className="flex-1 bg-green-600 hover:bg-green-700"
                    >
                      <CheckCircle className="h-4 w-4 mr-1" />
                      Aprovar
                    </Button>
                    <Button 
                      variant="destructive" 
                      onClick={rejectDocument}
                      disabled={!rejectionReason.trim()}
                      className="flex-1"
                    >
                      <XCircle className="h-4 w-4 mr-1" />
                      Rejeitar
                    </Button>
                  </div>
                )}
              </CardContent>
            </Card>
          ) : (
            <Card>
              <CardContent className="flex items-center justify-center h-64">
                <div className="text-center text-gray-500">
                  <FileText className="h-12 w-12 mx-auto mb-2" />
                  <p>Selecione um documento para validar</p>
                </div>
              </CardContent>
            </Card>
          )}
        </div>
      </div>
    </div>
  );
}

// apps/aio-app/src/routes/(dashboard)/documents/+page.svelte
<script lang="ts">
	import { enhance } from '$app/forms';
	import type { PageData, ActionData } from './$types';

	let { data, form }: { data: PageData; form: ActionData } = $props();

	let uploadFile: File | null = $state(null);
	let selectedType = $state('VACCINATION_CARD');
	let isUploading = $state(false);

	async function handleUpload(e: Event) {
		e.preventDefault();
		if (!uploadFile || !data.studentId) return;

		isUploading = true;

		try {
			// 1. Get presigned URL via action
			const formData = new FormData();
			formData.append('name', uploadFile.name);
			formData.append('type', uploadFile.type);
			formData.append('documentType', selectedType);
			formData.append('studentId', data.studentId);

			const response = await fetch('?/getUploadUrl', {
				method: 'POST',
				body: formData
			});

			const result = await response.json();
			// result is stringified JSON from SvelteKit action
			const actionResult = JSON.parse(result.data);
			
			if (actionResult[1]?.uploadUrl) {
				const uploadUrl = actionResult[1].uploadUrl;
				
				// 2. Upload to R2 directly from client
				await fetch(uploadUrl, {
					method: 'PUT',
					body: uploadFile,
					headers: {
						'Content-Type': uploadFile.type
					}
				});

				alert('Documento enviado com sucesso!');
				window.location.reload();
			}
		} catch (err) {
			console.error(err);
			alert('Falha ao enviar documento.');
		} finally {
			isUploading = false;
		}
	}
</script>

<div class="p-6">
	<h1 class="text-2xl font-bold mb-6">Documentos</h1>

	{#if data.isStudent}
		<!-- Student View: Upload and My Documents -->
		<div class="grid grid-cols-1 lg:grid-cols-3 gap-8">
			<div class="lg:col-span-1 bg-white p-6 rounded shadow h-fit">
				<h2 class="text-xl font-semibold mb-4">Enviar Novo Documento</h2>
				<form onsubmit={handleUpload}>
					<div class="mb-4">
						<label class="block text-sm font-medium text-gray-700" for="docType">Tipo de Documento</label>
						<select bind:value={selectedType} id="docType" class="mt-1 block w-full border rounded-md px-3 py-2">
							<option value="VACCINATION_CARD">Cartão de Vacinação</option>
							<option value="PROFESSIONAL_ID">Identidade Profissional (Crefito)</option>
							<option value="COMMITMENT_CONTRACT">Termo de Compromisso</option>
							<option value="ADMISSION_FORM">Ficha de Admissão</option>
							<option value="BADGE_PICTURE">Foto para Crachá</option>
							<option value="OTHER">Outro</option>
						</select>
					</div>

					<div class="mb-4">
						<label class="block text-sm font-medium text-gray-700" for="file">Arquivo</label>
						<input
							type="file"
							id="file"
							onchange={(e) => (uploadFile = (e.target as HTMLInputElement).files?.[0] || null)}
							required
							class="mt-1 block w-full text-sm text-gray-500 file:mr-4 file:py-2 file:px-4 file:rounded-md file:border-0 file:text-sm file:font-semibold file:bg-blue-50 file:text-blue-700 hover:file:bg-blue-100"
						/>
					</div>

					<button
						type="submit"
						disabled={isUploading}
						class="w-full bg-blue-600 text-white px-4 py-2 rounded hover:bg-blue-700 font-medium disabled:bg-blue-300"
					>
						{isUploading ? 'Enviando...' : 'Enviar Documento'}
					</button>
				</form>
			</div>

			<div class="lg:col-span-2 bg-white p-6 rounded shadow">
				<h2 class="text-xl font-semibold mb-4">Meus Documentos</h2>
				{#if data.documents.length === 0}
					<p class="text-gray-500 italic">Você ainda não enviou nenhum documento.</p>
				{:else}
					<div class="space-y-4">
						{#each data.documents as doc}
							<div class="border rounded p-4 flex justify-between items-center">
								<div>
									<p class="font-medium">{doc.name}</p>
									<p class="text-xs text-gray-500">{doc.type} • {new Date(doc.createdAt).toLocaleDateString()}</p>
								</div>
								<div class="flex items-center gap-4">
									<span class="px-2 py-1 rounded text-xs font-bold {doc.status === 'APPROVED' ? 'bg-green-100 text-green-800' : doc.status === 'REJECTED' ? 'bg-red-100 text-red-800' : 'bg-yellow-100 text-yellow-800'}">
										{doc.status}
									</span>
									{#if doc.status === 'REJECTED'}
										<p class="text-xs text-red-600 max-w-xs">{doc.rejectionReason}</p>
									{/if}
								</div>
							</div>
						{/each}
					</div>
				{/if}
			</div>
		</div>
	{:else}
		<!-- Supervisor/Admin View: Verification Queue -->
		<div class="bg-white p-6 rounded shadow">
			<h2 class="text-xl font-semibold mb-4">Fila de Verificação</h2>
			<div class="overflow-x-auto">
				<table class="min-w-full divide-y divide-gray-200">
					<thead class="bg-gray-50">
						<tr>
							<th class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase">Estudante</th>
							<th class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase">Documento</th>
							<th class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase">Status</th>
							<th class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase">Ações</th>
						</tr>
					</thead>
					<tbody class="bg-white divide-y divide-gray-200">
						{#each data.documents as doc}
							<tr>
								<td class="px-6 py-4 whitespace-nowrap text-sm text-gray-900">
									{doc.student.user.name}
								</td>
								<td class="px-6 py-4 whitespace-nowrap text-sm text-gray-500">
									<div>{doc.name}</div>
									<div class="text-xs">{doc.type}</div>
								</td>
								<td class="px-6 py-4 whitespace-nowrap">
									<span class="px-2 py-1 rounded text-xs font-bold {doc.status === 'APPROVED' ? 'bg-green-100 text-green-800' : doc.status === 'REJECTED' ? 'bg-red-100 text-red-800' : 'bg-yellow-100 text-yellow-800'}">
										{doc.status}
									</span>
								</td>
								<td class="px-6 py-4 whitespace-nowrap text-sm font-medium">
									<div class="flex gap-2">
										<a href="/documents/{doc.id}" class="text-blue-600 hover:underline">Ver</a>
										{#if doc.status === 'PENDING'}
											<form method="POST" action="?/approve" use:enhance>
												<input type="hidden" name="id" value={doc.id} />
												<button type="submit" class="text-green-600 hover:underline">Aprovar</button>
											</form>
											<button onclick={() => {
												const reason = prompt('Motivo da rejeição:');
												if (reason) {
													const formData = new FormData();
													formData.append('id', doc.id);
													formData.append('reason', reason);
													fetch('?/reject', { method: 'POST', body: formData }).then(() => window.location.reload());
												}
											}} class="text-red-600 hover:underline">Rejeitar</button>
										{/if}
									</div>
								</td>
							</tr>
						{/each}
					</tbody>
				</table>
			</div>
		</div>
	{/if}
</div>
