// src/lib/components/ui/Button.svelte
<script lang="ts">
	import type { HTMLButtonAttributes } from "svelte/elements";
	import { type Snippet } from "svelte";
	import { cn } from "$lib/utils";

	interface Props extends HTMLButtonAttributes {
		children: Snippet;
		variant?: "primary" | "secondary" | "outline" | "ghost" | "danger";
		size?: "sm" | "md" | "lg" | "icon";
		class?: string;
	}

	let { children, variant = "primary", size = "md", class: className, ...props }: Props = $props();

	const variants = {
		primary: "bg-blue-600 text-white hover:bg-blue-700 shadow-sm border border-blue-700",
		secondary: "bg-gray-100 text-gray-900 hover:bg-gray-200 border border-gray-200",
		outline: "border border-gray-300 bg-white hover:bg-gray-50 text-gray-700 shadow-xs",
		ghost: "bg-transparent hover:bg-gray-100 text-gray-600",
		danger: "bg-red-600 text-white hover:bg-red-700 shadow-sm border border-red-700",
	};

	const sizes = {
		sm: "px-3 py-1.5 text-xs h-8",
		md: "px-4 py-2 text-sm h-10",
		lg: "px-6 py-3 text-base h-12",
		icon: "p-2 h-10 w-10",
	};

	const baseClass =
		"inline-flex items-center justify-center rounded-lg font-medium transition-all focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-blue-500 disabled:pointer-events-none disabled:opacity-50 cursor-pointer active:scale-[0.98]";
</script>

<button class={cn(baseClass, variants[variant], sizes[size], className)} {...props}>
	{@render children()}
</button>

// apps/web/src/components/ui/button.tsx
import * as React from "react";
import { Slot } from "@radix-ui/react-slot";
import { cva, type VariantProps } from "class-variance-authority";

import { cn } from "@web/lib/utils";

const buttonVariants = cva(
	"inline-flex items-center justify-center gap-2 whitespace-nowrap rounded-md text-sm font-medium transition-all disabled:pointer-events-none disabled:opacity-50 [&_svg]:pointer-events-none [&_svg:not([class*='size-'])]:size-4 shrink-0 [&_svg]:shrink-0 outline-none focus-visible:border-ring focus-visible:ring-ring/50 focus-visible:ring-[3px] aria-invalid:ring-destructive/20 dark:aria-invalid:ring-destructive/40 aria-invalid:border-destructive",
	{
		variants: {
			variant: {
				default:
					"bg-primary text-primary-foreground shadow-xs hover:bg-primary/90",
				destructive:
					"bg-destructive text-white shadow-xs hover:bg-destructive/90 focus-visible:ring-destructive/20 dark:focus-visible:ring-destructive/40 dark:bg-destructive/60",
				outline:
					"border bg-background shadow-xs hover:bg-accent hover:text-accent-foreground dark:bg-input/30 dark:border-input dark:hover:bg-input/50",
				secondary:
					"bg-secondary text-secondary-foreground shadow-xs hover:bg-secondary/80",
				ghost:
					"hover:bg-accent hover:text-accent-foreground dark:hover:bg-accent/50",
				link: "text-primary underline-offset-4 hover:underline",
			},
			size: {
				default: "h-9 px-4 py-2 has-[>svg]:px-3",
				sm: "h-8 rounded-md gap-1.5 px-3 has-[>svg]:px-2.5",
				lg: "h-10 rounded-md px-6 has-[>svg]:px-4",
				icon: "size-9",
			},
		},
		defaultVariants: {
			variant: "default",
			size: "default",
		},
	}
);

function Button({
	className,
	variant,
	size,
	asChild = false,
	...props
}: React.ComponentProps<"button"> &
	VariantProps<typeof buttonVariants> & {
		asChild?: boolean;
	}) {
	const Comp = asChild ? Slot : "button";

	return (
		<Comp
			data-slot="button"
			className={cn(buttonVariants({ variant, size, className }))}
			{...props}
		/>
	);
}

export { Button, buttonVariants };
