// src/lib/components/ui/Input.svelte
<script lang="ts">
	import type { HTMLInputAttributes } from "svelte/elements";
	import { cn } from "$lib/utils";

	interface Props extends HTMLInputAttributes {
		label?: string;
		error?: string;
		class?: string;
	}

	let {
		label,
		error,
		class: className,
		id = Math.random().toString(36).substring(2, 9),
		value = $bindable(),
		...props
	}: Props = $props();
</script>

<div class="w-full space-y-1.5">
	{#if label}
		<label for={id} class="text-sm leading-none font-medium text-gray-700">
			{label}
		</label>
	{/if}
	<input
		{id}
		bind:value
		class={cn(
			"flex h-10 w-full rounded-lg border border-gray-200 bg-white px-3 py-2 text-sm shadow-xs transition-all placeholder:text-gray-400 focus-visible:border-transparent focus-visible:ring-2 focus-visible:ring-blue-500 focus-visible:outline-none disabled:cursor-not-allowed disabled:opacity-50",
			error && "border-red-500 focus-visible:ring-red-500",
			className
		)}
		{...props}
	/>
	{#if error}
		<p class="text-xs font-medium text-red-500">{error}</p>
	{/if}
</div>

// apps/web/src/components/ui/input.tsx
import * as React from "react";

import { cn } from "@web/lib/utils";

function Input({ className, type, ...props }: React.ComponentProps<"input">) {
	return (
		<input
			type={type}
			data-slot="input"
			className={cn(
				"file:text-foreground placeholder:text-muted-foreground selection:bg-primary selection:text-primary-foreground dark:bg-input/30 border-input flex h-9 w-full min-w-0 rounded-md border bg-transparent px-3 py-1 text-base shadow-xs transition-[color,box-shadow] outline-none file:inline-flex file:h-7 file:border-0 file:bg-transparent file:text-sm file:font-medium disabled:pointer-events-none disabled:cursor-not-allowed disabled:opacity-50 md:text-sm",
				"focus-visible:border-ring focus-visible:ring-ring/50 focus-visible:ring-[3px]",
				"aria-invalid:ring-destructive/20 dark:aria-invalid:ring-destructive/40 aria-invalid:border-destructive",
				className
			)}
			{...props}
		/>
	);
}

export { Input };
