// apps/web/components/ui/badge.tsx
import * as React from "react";
import { cva, type VariantProps } from "class-variance-authority";

import { cn } from "../../lib/utils";

const badgeVariants = cva(
	"inline-flex items-center rounded-full border px-2.5 py-0.5 text-xs font-semibold transition-colors focus:outline-none focus:ring-2 focus:ring-ring focus:ring-offset-2",
	{
		variants: {
			variant: {
				default:
					"border-transparent bg-primary text-primary-foreground hover:bg-primary/80",
				secondary:
					"border-transparent bg-secondary text-secondary-foreground hover:bg-secondary/80",
				destructive:
					"border-transparent bg-destructive text-destructive-foreground hover:bg-destructive/80",
				outline: "text-foreground",
			},
		},
		defaultVariants: {
			variant: "default",
		},
	}
);

export interface BadgeProps
	extends React.HTMLAttributes<HTMLDivElement>,
		VariantProps<typeof badgeVariants> {}

function Badge({ className, variant, ...props }: BadgeProps) {
	return (
		<div className={cn(badgeVariants({ variant }), className)} {...props} />
	);
}

export { Badge, badgeVariants };

// src/lib/components/ui/Badge.svelte
<script lang="ts">
	import { type Snippet } from "svelte";
	import { cn } from "$lib/utils";

	interface Props {
		children: Snippet;
		variant?: "success" | "warning" | "error" | "info" | "neutral";
		class?: string;
	}

	let { children, variant = "neutral", class: className }: Props = $props();

	const variants = {
		success: "bg-green-50 text-green-700 border-green-200",
		warning: "bg-yellow-50 text-yellow-700 border-yellow-200",
		error: "bg-red-50 text-red-700 border-red-200",
		info: "bg-blue-50 text-blue-700 border-blue-200",
		neutral: "bg-gray-50 text-gray-700 border-gray-200",
	};
</script>

<span
	class={cn(
		"inline-flex items-center rounded-full border px-2.5 py-0.5 text-xs font-semibold transition-colors",
		variants[variant],
		className
	)}
>
	{@render children()}
</span>
