// apps/web_crude/src/components/ui/card.tsx
import * as React from "react";

import { cn } from "@web/lib/utils";

function Card({ className, ...props }: React.ComponentProps<"div">) {
	return (
		<div
			data-slot="card"
			className={cn(
				"bg-card text-card-foreground flex flex-col gap-6 rounded-xl border py-6 shadow-sm",
				className
			)}
			{...props}
		/>
	);
}

function CardHeader({ className, ...props }: React.ComponentProps<"div">) {
	return (
		<div
			data-slot="card-header"
			className={cn(
				"@container/card-header grid auto-rows-min grid-rows-[auto_auto] items-start gap-1.5 px-6 has-data-[slot=card-action]:grid-cols-[1fr_auto] [.border-b]:pb-6",
				className
			)}
			{...props}
		/>
	);
}

function CardTitle({ className, ...props }: React.ComponentProps<"div">) {
	return (
		<div
			data-slot="card-title"
			className={cn("leading-none font-semibold", className)}
			{...props}
		/>
	);
}

function CardDescription({ className, ...props }: React.ComponentProps<"div">) {
	return (
		<div
			data-slot="card-description"
			className={cn("text-muted-foreground text-sm", className)}
			{...props}
		/>
	);
}

function CardAction({ className, ...props }: React.ComponentProps<"div">) {
	return (
		<div
			data-slot="card-action"
			className={cn(
				"col-start-2 row-span-2 row-start-1 self-start justify-self-end",
				className
			)}
			{...props}
		/>
	);
}

function CardContent({ className, ...props }: React.ComponentProps<"div">) {
	return (
		<div
			data-slot="card-content"
			className={cn("px-6", className)}
			{...props}
		/>
	);
}

function CardFooter({ className, ...props }: React.ComponentProps<"div">) {
	return (
		<div
			data-slot="card-footer"
			className={cn("flex items-center px-6 [.border-t]:pt-6", className)}
			{...props}
		/>
	);
}

export {
	Card,
	CardHeader,
	CardFooter,
	CardTitle,
	CardAction,
	CardDescription,
	CardContent,
};

// src/lib/components/ui/Card.svelte
<script lang="ts">
	import { type Snippet } from 'svelte';
	import { cn } from '$lib/utils';

	interface Props {
		children: Snippet;
		title?: string;
		description?: string;
		footer?: Snippet;
		headerAction?: Snippet;
		class?: string;
		contentClass?: string;
	}

	let {
		children,
		title,
		description,
		footer,
		headerAction,
		class: className,
		contentClass
	}: Props = $props();
</script>

<div
	class={cn(
		'flex flex-col overflow-hidden rounded-xl border border-gray-100 bg-white shadow-sm',
		className
	)}
>
	{#if title || description || headerAction}
		<div class="flex items-start justify-between gap-4 p-6 pb-4">
			<div class="space-y-1">
				{#if title}
					<h3 class="text-lg leading-none font-semibold tracking-tight text-gray-900">{title}</h3>
				{/if}
				{#if description}
					<p class="text-sm text-gray-500">{description}</p>
				{/if}
			</div>
			{#if headerAction}
				{@render headerAction()}
			{/if}
		</div>
	{/if}

	<div class={cn('flex-1 p-6 pt-0', contentClass)}>
		{@render children()}
	</div>

	{#if footer}
		<div class="mt-auto border-t border-gray-50 bg-gray-50/30 p-6 px-6 py-4 pt-0">
			{@render footer()}
		</div>
	{/if}
</div>
