// src/lib/components/ui/Card.svelte
<script lang="ts">
	import { type Snippet } from 'svelte';
	import { cn } from '$lib/utils';

	interface Props {
		children: Snippet;
		title?: string;
		description?: string;
		footer?: Snippet;
		headerAction?: Snippet;
		class?: string;
		contentClass?: string;
	}

	let {
		children,
		title,
		description,
		footer,
		headerAction,
		class: className,
		contentClass
	}: Props = $props();
</script>

<div
	class={cn(
		'flex flex-col overflow-hidden rounded-xl border border-gray-100 bg-white shadow-sm',
		className
	)}
>
	{#if title || description || headerAction}
		<div class="flex items-start justify-between gap-4 p-6 pb-4">
			<div class="space-y-1">
				{#if title}
					<h3 class="text-lg leading-none font-semibold tracking-tight text-gray-900">{title}</h3>
				{/if}
				{#if description}
					<p class="text-sm text-gray-500">{description}</p>
				{/if}
			</div>
			{#if headerAction}
				{@render headerAction()}
			{/if}
		</div>
	{/if}

	<div class={cn('flex-1 p-6 pt-0', contentClass)}>
		{@render children()}
	</div>

	{#if footer}
		<div class="mt-auto border-t border-gray-50 bg-gray-50/30 p-6 px-6 py-4 pt-0">
			{@render footer()}
		</div>
	{/if}
</div>

// apps/web/components/ui/card.tsx
import * as React from "react";

import { cn } from "../../lib/utils";

const Card = React.forwardRef<
	HTMLDivElement,
	React.HTMLAttributes<HTMLDivElement>
>(({ className, ...props }, ref) => (
	<div
		ref={ref}
		className={cn(
			"bg-card text-card-foreground rounded-lg border shadow-sm",
			className
		)}
		{...props}
	/>
));
Card.displayName = "Card";

const CardHeader = React.forwardRef<
	HTMLDivElement,
	React.HTMLAttributes<HTMLDivElement>
>(({ className, ...props }, ref) => (
	<div
		ref={ref}
		className={cn("flex flex-col space-y-1.5 p-6", className)}
		{...props}
	/>
));
CardHeader.displayName = "CardHeader";

const CardTitle = React.forwardRef<
	HTMLDivElement,
	React.HTMLAttributes<HTMLDivElement>
>(({ className, ...props }, ref) => (
	<div
		ref={ref}
		className={cn(
			"text-2xl leading-none font-semibold tracking-tight",
			className
		)}
		{...props}
	/>
));
CardTitle.displayName = "CardTitle";

const CardDescription = React.forwardRef<
	HTMLDivElement,
	React.HTMLAttributes<HTMLDivElement>
>(({ className, ...props }, ref) => (
	<div
		ref={ref}
		className={cn("text-muted-foreground text-sm", className)}
		{...props}
	/>
));
CardDescription.displayName = "CardDescription";

const CardContent = React.forwardRef<
	HTMLDivElement,
	React.HTMLAttributes<HTMLDivElement>
>(({ className, ...props }, ref) => (
	<div ref={ref} className={cn("p-6 pt-0", className)} {...props} />
));
CardContent.displayName = "CardContent";

const CardFooter = React.forwardRef<
	HTMLDivElement,
	React.HTMLAttributes<HTMLDivElement>
>(({ className, ...props }, ref) => (
	<div
		ref={ref}
		className={cn("flex items-center p-6 pt-0", className)}
		{...props}
	/>
));
CardFooter.displayName = "CardFooter";

export {
	Card,
	CardHeader,
	CardFooter,
	CardTitle,
	CardDescription,
	CardContent,
};
