// src/lib/components/layout/Sidebar.svelte
<script lang="ts">
	import { page } from '$app/state';
	import {
		LayoutDashboard,
		Hospital,
		GraduationCap,
		Building2,
		Users,
		User,
		Files,
		Settings,
		ChevronRight,
		Layers,
		Clock,
		Calendar,
		Link
	} from 'lucide-svelte';
	import { cn } from '$lib/utils';

	const navItems = [
		{ name: 'Dashboard', href: '/dashboard', icon: LayoutDashboard },
		{ name: 'Hospitais', href: '/hospitals', icon: Hospital },
		{ name: 'Preceptores', href: '/preceptors', icon: User },
		{ name: 'Escolas', href: '/schools', icon: GraduationCap },
		{ name: 'Turmas', href: '/classes', icon: Layers },
		{ name: 'Organizações', href: '/organizations', icon: Building2 },
		{ name: 'Estudantes', href: '/students', icon: Users },
		{ name: 'Vínculos', href: '/placements', icon: Link },
		{ name: 'Documentos', href: '/documents', icon: Files },
		{ name: 'Disponibilidade', href: '/availability', icon: Clock },
		{ name: 'Plantões', href: '/shifts', icon: Calendar }
	];

	const isActive = (href: string) => {
		if (href === '/dashboard') return page.url.pathname === '/dashboard';
		return page.url.pathname.startsWith(href);
	};
</script>

<aside class="flex hidden h-full w-72 flex-col border-r border-gray-100 bg-white shadow-sm md:flex">
	<div class="p-8">
		<div class="flex items-center gap-3">
			<div
				class="flex h-10 w-10 items-center justify-center rounded-xl bg-blue-600 shadow-lg shadow-blue-200"
			>
				<Building2 class="h-6 w-6 text-white" />
			</div>
			<h1
				class="bg-gradient-to-r from-blue-700 to-blue-500 bg-clip-text text-xl font-bold text-transparent"
			>
				Preceptoria
			</h1>
		</div>
	</div>

	<nav class="flex-1 space-y-1.5 overflow-y-auto px-4">
		<p class="mb-4 px-4 text-[10px] font-bold tracking-widest text-gray-400 uppercase">
			Menu Principal
		</p>

		{#each navItems as item}
			{@const active = isActive(item.href)}
			<a
				href={item.href}
				class={cn(
					'group flex items-center justify-between rounded-xl px-4 py-3 text-sm font-medium transition-all duration-200',
					active
						? 'bg-blue-50 text-blue-700 shadow-sm shadow-blue-50'
						: 'text-gray-500 hover:bg-gray-50 hover:text-gray-900'
				)}
			>
				<div class="flex items-center gap-3">
					<item.icon
						class={cn(
							'h-5 w-5 transition-colors',
							active ? 'text-blue-600' : 'text-gray-400 group-hover:text-gray-600'
						)}
					/>
					<span>{item.name}</span>
				</div>
				{#if active}
					<ChevronRight class="h-4 w-4 text-blue-400" />
				{/if}
			</a>
		{/each}
	</nav>

	<div class="mt-auto border-t border-gray-50 p-4">
		<a
			href="/settings"
			class="flex items-center gap-3 rounded-xl px-4 py-3 text-sm font-medium text-gray-500 transition-colors hover:bg-gray-50 hover:text-gray-900"
		>
			<Settings class="h-5 w-5 text-gray-400" />
			<span>Configurações</span>
		</a>
	</div>
</aside>

// packages/web/components/layout/Sidebar.tsx
"use client"

import { memo } from "react"
import { Home, BookOpen, Users, User, Calendar, FileText, Settings, GraduationCap } from "lucide-react"
import { SearchInput } from "@/components/ui/SearchInput"
import { SearchResults } from "@/components/ui/SearchResults"
import { useSearch } from "@/hooks/useSearch"
import type { MenuItem } from "@/types"

const MENU_ITEMS: MenuItem[] = [
  { title: "Dashboard", icon: Home, href: "/dashboard", isActive: true },
  { title: "Cursos", icon: BookOpen, href: "/cursos", isActive: false },
  { title: "Turmas", icon: Users, href: "/turmas", isActive: false },
  { title: "Alunos", icon: User, href: "/alunos", isActive: false },
  { title: "Plantões", icon: Calendar, href: "/plantoes", isActive: false },
]

export const Sidebar = memo(() => {
  const { query, setQuery, results, hasResults } = useSearch()

  return (
    <div className="fixed left-0 top-0 h-screen w-80 bg-white border-r border-gray-200 flex flex-col z-40">
      {/* Header */}
      <div className="p-4 border-b border-gray-200 flex-shrink-0">
        <div className="flex items-center space-x-3 mb-4">
          <div className="p-2 bg-blue-100 rounded-lg">
            <GraduationCap className="h-6 w-6 text-blue-600" />
          </div>
          <div>
            <h2 className="font-semibold text-gray-900">Preceptoria</h2>
            <p className="text-xs text-gray-600">Sistema de Gestão</p>
          </div>
        </div>

        <SearchInput value={query} onChange={setQuery} placeholder="Buscar alunos, turmas, cursos..." />

        {query && (
          <div className="mt-2 bg-white border border-gray-200 rounded-md shadow-sm max-h-48 overflow-y-auto">
            <SearchResults results={results} />
          </div>
        )}
      </div>

      {/* Content */}
      <div className="flex-1 flex flex-col min-h-0">
        <div className="flex-1 p-4 overflow-y-auto">
          {/* Main Navigation */}
          <div className="mb-8">
            <h3 className="text-xs font-semibold text-gray-500 uppercase tracking-wider mb-3">Navegação Principal</h3>
            <nav className="space-y-1">
              {MENU_ITEMS.map((item) => (
                <a
                  key={item.title}
                  href={item.href}
                  className={`flex items-center space-x-3 px-3 py-2 text-sm font-medium rounded-md transition-colors ${
                    item.isActive ? "bg-blue-100 text-blue-700" : "text-gray-700 hover:bg-gray-100 hover:text-gray-900"
                  }`}
                >
                  <item.icon className="h-5 w-5" />
                  <span>{item.title}</span>
                </a>
              ))}
            </nav>
          </div>

          {/* Quick Actions */}
          <div>
            <h3 className="text-xs font-semibold text-gray-500 uppercase tracking-wider mb-3">Ações Rápidas</h3>
            <nav className="space-y-1">
              <a
                href="/relatorios"
                className="flex items-center space-x-3 px-3 py-2 text-sm font-medium text-gray-700 rounded-md hover:bg-gray-100 hover:text-gray-900 transition-colors"
              >
                <FileText className="h-5 w-5" />
                <span>Relatórios</span>
              </a>
            </nav>
          </div>
        </div>

        {/* User Profile */}
        <div className="p-4 border-t border-gray-200 flex-shrink-0">
          <div className="flex items-center space-x-3 px-3 py-2">
            <div className="h-10 w-10 bg-blue-100 rounded-full flex items-center justify-center">
              <User className="h-6 w-6 text-blue-600" />
            </div>
            <div className="flex-1 min-w-0">
              <p className="text-sm font-medium text-gray-900 truncate">Prof. João Silva</p>
              <p className="text-xs text-gray-600 truncate">Supervisor</p>
            </div>
            <button className="p-1.5 text-gray-400 hover:text-gray-600 hover:bg-gray-100 rounded-md transition-colors">
              <Settings className="h-4 w-4" />
            </button>
          </div>
        </div>
      </div>
    </div>
  )
})

Sidebar.displayName = "Sidebar"
