// apps/web/components/layout/Header.tsx
import { memo } from "react";
import { Bell } from "lucide-react";

interface HeaderProps {
	title: string;
	subtitle: string;
	notificationCount?: number;
}

export const Header = memo<HeaderProps>(
	({ title, subtitle, notificationCount = 0 }) => {
		return (
			<header className="border-b bg-white shadow-sm">
				<div className="px-6 lg:px-8">
					<div className="flex items-center justify-between py-4">
						<div>
							<h1 className="text-2xl font-bold text-gray-900">{title}</h1>
							<p className="text-sm text-gray-600">{subtitle}</p>
						</div>

						<div className="relative">
							<button className="rounded-full p-2 text-gray-400 transition-colors hover:bg-gray-100 hover:text-gray-600">
								<Bell className="h-6 w-6" />
								{notificationCount > 0 && (
									<span className="absolute -top-1 -right-1 flex h-4 w-4 items-center justify-center rounded-full bg-red-500 text-xs text-white">
										{notificationCount}
									</span>
								)}
							</button>
						</div>
					</div>
				</div>
			</header>
		);
	}
);

Header.displayName = "Header";

// src/lib/components/layout/Header.svelte
<script lang="ts">
	import { Bell, Search, User, LogOut } from "lucide-svelte";
	import { authClient } from "$lib/auth-client";
	import { goto } from "$app/navigation";

	let { user }: { user: { name: string; role: string } | null } = $props();

	async function handleLogout() {
		await authClient.signOut();
		await goto("/login");
	}
</script>

<header
	class="sticky top-0 z-30 flex h-20 items-center justify-between border-b border-gray-100 bg-white/80 px-8 backdrop-blur-md"
>
	<div class="flex flex-1 items-center gap-4">
		<div class="relative hidden w-full max-w-md lg:block">
			<Search class="absolute top-1/2 left-3 h-4 w-4 -translate-y-1/2 text-gray-400" />
			<input
				type="text"
				placeholder="Pesquisar..."
				class="w-full rounded-full border-none bg-gray-50 py-2 pr-4 pl-10 text-sm transition-all focus:ring-2 focus:ring-blue-100"
			/>
		</div>
	</div>

	<div class="flex items-center gap-6">
		<button class="relative p-2 text-gray-400 transition-colors hover:text-gray-600">
			<Bell class="h-5 w-5" />
			<span class="absolute top-2 right-2 h-2 w-2 rounded-full border-2 border-white bg-red-500"
			></span>
		</button>

		<div class="h-8 w-px bg-gray-100"></div>

		<div class="flex items-center gap-4">
			<div class="hidden text-right sm:block">
				<p class="text-sm font-semibold text-gray-900">{user?.name || "Usuário"}</p>
				<p class="text-xs font-medium tracking-tight text-gray-500 uppercase">
					{user?.role || "Visitante"}
				</p>
			</div>

			<div class="group relative">
				<div
					class="flex h-10 w-10 cursor-pointer items-center justify-center overflow-hidden rounded-xl bg-gradient-to-tr from-blue-600 to-indigo-500 font-bold text-white shadow-md shadow-blue-100 transition-transform active:scale-95"
				>
					{#if user?.name}
						{user.name.charAt(0)}
					{:else}
						<User class="h-5 w-5" />
					{/if}
				</div>

				<!-- Simple Dropdown Placeholder -->
				<div
					class="invisible absolute right-0 mt-2 w-48 origin-top-right transform rounded-xl border border-gray-100 bg-white py-2 opacity-0 shadow-xl transition-all duration-200 group-hover:visible group-hover:opacity-100"
				>
					<div class="px-2">
						<button
							onclick={handleLogout}
							class="flex w-full items-center gap-3 rounded-lg px-3 py-2 text-sm font-bold text-red-600 transition-colors hover:bg-red-50"
						>
							<LogOut class="h-4 w-4" />
							Sair da conta
						</button>
					</div>
				</div>
			</div>
		</div>
	</div>
</header>
